CREATE TABLE users(

	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL UNIQUE,
	fist_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	created_at DATE NOT NULL,
	locked BIT NOT NULL DEFAULT 0,
	status ENUM('ACTIVE', 'DEACTIVED', 'PENDING', 'SUSPENDED') NOT NULL DEFAULT('PENDING'),	
	
	PRIMARY KEY(id)	
);

CREATE TABLE prefixes(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	user BIGINT UNSIGNED NOT NULL,
	prefix VARCHAR(20) NULL UNIQUE,
	
	PRIMARY KEY(id),
	FOREIGN KEY(user) REFERENCES users(id)
);

CREATE TABLE links(
	id VARCHAR(10) NOT NULL,
	prefix BIGINT UNSIGNED NOT NULL,
	destine VARCHAR(2048) NOT NULL,
			
	PRIMARY KEY(id),
	FOREIGN KEY(prefix) REFERENCES prefixes(id),
	CONSTRAINT prefix_destine_unique UNIQUE(prefix, destine(191))
);