CREATE TABLE users(

	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL UNIQUE,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	created_at DATE NOT NULL,
	locked BIT NOT NULL DEFAULT 0,
	status ENUM('ACTIVE', 'DEACTIVATED', 'PENDING', 'SUSPENDED') NOT NULL DEFAULT 'PENDING',	
	
	PRIMARY KEY(id)	
);

CREATE TABLE prefixes(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id BIGINT UNSIGNED NOT NULL,
	prefix VARCHAR(20) NULL UNIQUE,
	
	PRIMARY KEY(id),
	FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE links(
	id VARCHAR(10) NOT NULL,
	prefix_id BIGINT UNSIGNED NOT NULL,
	destination VARCHAR(2048) NOT NULL,
			
	PRIMARY KEY(id),
	FOREIGN KEY(prefix_id) REFERENCES prefixes(id)
);